//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaxAndromeda.Instar {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PaxAndromeda.Instar.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while attempting to withhold membership for &lt;@{0}&gt;: User is already a member..
        /// </summary>
        public static string Command_AutoMemberHold_Error_AlreadyMember {
            get {
                return ResourceManager.GetString("Command_AutoMemberHold_Error_AlreadyMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while attempting to withhold membership for &lt;@{0}&gt;: User already has an effective membership hold..
        /// </summary>
        public static string Command_AutoMemberHold_Error_AMHAlreadyExists {
            get {
                return ResourceManager.GetString("Command_AutoMemberHold_Error_AMHAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while attempting to withhold membership for &lt;@{0}&gt;: User is not a guild member..
        /// </summary>
        public static string Command_AutoMemberHold_Error_NotGuildMember {
            get {
                return ResourceManager.GetString("Command_AutoMemberHold_Error_NotGuildMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while attempting to withhold membership for &lt;@{0}&gt;: An unexpected error occurred while configuring the AMH..
        /// </summary>
        public static string Command_AutoMemberHold_Error_Unexpected {
            get {
                return ResourceManager.GetString("Command_AutoMemberHold_Error_Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership for user &lt;@{0}&gt; has been withheld. Staff will be notified in one week to review..
        /// </summary>
        public static string Command_AutoMemberHold_Success {
            get {
                return ResourceManager.GetString("Command_AutoMemberHold_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while attempting to remove auto member hold for &lt;@{0}&gt;: User does not have an active auto member hold..
        /// </summary>
        public static string Command_AutoMemberUnhold_Error_NoActiveHold {
            get {
                return ResourceManager.GetString("Command_AutoMemberUnhold_Error_NoActiveHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while attempting to remove auto member hold for &lt;@{0}&gt;: User is not a guild member..
        /// </summary>
        public static string Command_AutoMemberUnhold_Error_NotGuildMember {
            get {
                return ResourceManager.GetString("Command_AutoMemberUnhold_Error_NotGuildMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while attempting to remove auto member hold for &lt;@{0}&gt;: An unexpected error has occurred while removing the AMH..
        /// </summary>
        public static string Command_AutoMemberUnhold_Error_Unexpected {
            get {
                return ResourceManager.GetString("Command_AutoMemberUnhold_Error_Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto member hold for user &lt;@{0}&gt; has been removed..
        /// </summary>
        public static string Command_AutoMemberUnhold_Success {
            get {
                return ResourceManager.GetString("Command_AutoMemberUnhold_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, the staff will not accelerate this process by request..
        /// </summary>
        public static string Command_CheckEligibility_AMH_ContactStaff {
            get {
                return ResourceManager.GetString("Command_CheckEligibility_AMH_ContactStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your membership is currently on hold due to an administrative override. This means that you will not be granted the Member role automatically..
        /// </summary>
        public static string Command_CheckEligibility_AMH_MembershipWithheld {
            get {
                return ResourceManager.GetString("Command_CheckEligibility_AMH_MembershipWithheld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The staff will override an administrative hold in time when an evaluation of your behavior has been completed by the staff..
        /// </summary>
        public static string Command_CheckEligibility_AMH_WhatToDo {
            get {
                return ResourceManager.GetString("Command_CheckEligibility_AMH_WhatToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your activity has been flagged as unusual by our system. This can happen for a variety of reasons, including antisocial behavior, repeated rule violations in a short period of time, or other behavior that is deemed disruptive..
        /// </summary>
        public static string Command_CheckEligibility_AMH_Why {
            get {
                return ResourceManager.GetString("Command_CheckEligibility_AMH_Why", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :white_check_mark:.
        /// </summary>
        public static string Command_CheckEligibility_EligibleEmoji {
            get {
                return ResourceManager.GetString("Command_CheckEligibility_EligibleEmoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Eligibility.
        /// </summary>
        public static string Command_CheckEligibility_EmbedTitle {
            get {
                return ResourceManager.GetString("Command_CheckEligibility_EmbedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already a member!.
        /// </summary>
        public static string Command_CheckEligibility_Error_AlreadyMember {
            get {
                return ResourceManager.GetString("Command_CheckEligibility_Error_AlreadyMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error has occurred.  Please try again later..
        /// </summary>
        public static string Command_CheckEligibility_Error_Internal {
            get {
                return ResourceManager.GetString("Command_CheckEligibility_Error_Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the New Member or Member roles.  Please contact staff to have this corrected..
        /// </summary>
        public static string Command_CheckEligibility_Error_NoMemberRoles {
            get {
                return ResourceManager.GetString("Command_CheckEligibility_Error_NoMemberRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} **Introduction**.
        /// </summary>
        public static string Command_CheckEligibility_IntroductionEligibility {
            get {
                return ResourceManager.GetString("Command_CheckEligibility_IntroductionEligibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} **Join Age**.
        /// </summary>
        public static string Command_CheckEligibility_JoinAgeEligibility {
            get {
                return ResourceManager.GetString("Command_CheckEligibility_JoinAgeEligibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} **Messages** (last 24 hours).
        /// </summary>
        public static string Command_CheckEligibility_MessagesEligibility {
            get {
                return ResourceManager.GetString("Command_CheckEligibility_MessagesEligibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not posted an introduction in {0}..
        /// </summary>
        public static string Command_CheckEligibility_MissingItem_Introduction {
            get {
                return ResourceManager.GetString("Command_CheckEligibility_MissingItem_Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not posted {0} messages in the past {1} hours..
        /// </summary>
        public static string Command_CheckEligibility_MissingItem_Messages {
            get {
                return ResourceManager.GetString("Command_CheckEligibility_MissingItem_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have received a warning or moderator action..
        /// </summary>
        public static string Command_CheckEligibility_MissingItem_PunishmentReceived {
            get {
                return ResourceManager.GetString("Command_CheckEligibility_MissingItem_PunishmentReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are missing {0} {1} role..
        /// </summary>
        public static string Command_CheckEligibility_MissingItem_Role {
            get {
                return ResourceManager.GetString("Command_CheckEligibility_MissingItem_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not been on the server for {0} hours yet..
        /// </summary>
        public static string Command_CheckEligibility_MissingItem_TooYoung {
            get {
                return ResourceManager.GetString("Command_CheckEligibility_MissingItem_TooYoung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} **Mod Actions**.
        /// </summary>
        public static string Command_CheckEligibility_ModActionsEligibility {
            get {
                return ResourceManager.GetString("Command_CheckEligibility_ModActionsEligibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Auto Member System will run &lt;t:{0}:R&gt;. Membership eligibility is subject to change at the time of evaluation..
        /// </summary>
        public static string Command_CheckEligibility_NextRuntimeNote {
            get {
                return ResourceManager.GetString("Command_CheckEligibility_NextRuntimeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :x:.
        /// </summary>
        public static string Command_CheckEligibility_NotEligibleEmoji {
            get {
                return ResourceManager.GetString("Command_CheckEligibility_NotEligibleEmoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} **Roles**.
        /// </summary>
        public static string Command_CheckEligibility_RolesEligibility {
            get {
                return ResourceManager.GetString("Command_CheckEligibility_RolesEligibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At this time, &lt;@{0}&gt; is eligible for membership..
        /// </summary>
        public static string Command_Eligibility_EligibleText {
            get {
                return ResourceManager.GetString("Command_Eligibility_EligibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instar encountered an error while attempting to retrieve AMH details. If the user is otherwise eligible but is not being granted membership, it is possible that they are AMHed. Please try again later..
        /// </summary>
        public static string Command_Eligibility_Error_AmbiguousHold {
            get {
                return ResourceManager.GetString("Command_Eligibility_Error_AmbiguousHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Mod:** &lt;@{0}&gt;\r\n**Reason:**\r\n```{1}```\r\n**Date:** &lt;t:{2}:f&gt; (&lt;t:{2}:R&gt;).
        /// </summary>
        public static string Command_Eligibility_HoldFormat {
            get {
                return ResourceManager.GetString("Command_Eligibility_HoldFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At this time, &lt;@{0}&gt; is __not__ eligible for membership..
        /// </summary>
        public static string Command_Eligibility_IneligibleText {
            get {
                return ResourceManager.GetString("Command_Eligibility_IneligibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :warning: Possible Auto Member Hold.
        /// </summary>
        public static string Command_Eligibility_Section_AmbiguousHold {
            get {
                return ResourceManager.GetString("Command_Eligibility_Section_AmbiguousHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :warning: Auto Member Hold.
        /// </summary>
        public static string Command_Eligibility_Section_Hold {
            get {
                return ResourceManager.GetString("Command_Eligibility_Section_Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements.
        /// </summary>
        public static string Command_Eligibility_Section_Requirements {
            get {
                return ResourceManager.GetString("Command_Eligibility_Section_Requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to send a page to the entire staff team..
        /// </summary>
        public static string Command_Page_Error_FullTeamNotAuthorized {
            get {
                return ResourceManager.GetString("Command_Page_Error_FullTeamNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send page. The &apos;All&apos; team does not have a teamleader. If intended to page the owner, please select the Owner as the team..
        /// </summary>
        public static string Command_Page_Error_NoAllTeamlead {
            get {
                return ResourceManager.GetString("Command_Page_Error_NoAllTeamlead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to use this command..
        /// </summary>
        public static string Command_Page_Error_NotAuthorized {
            get {
                return ResourceManager.GetString("Command_Page_Error_NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to process command due to an internal server error..
        /// </summary>
        public static string Command_Page_Error_Unexpected {
            get {
                return ResourceManager.GetString("Command_Page_Error_Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a __**TEST**__ page..
        /// </summary>
        public static string Command_Page_TestPageMessage {
            get {
                return ResourceManager.GetString("Command_Page_TestPageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report expired. Please try again..
        /// </summary>
        public static string Command_ReportUser_ReportExpired {
            get {
                return ResourceManager.GetString("Command_ReportUser_ReportExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your report has been sent..
        /// </summary>
        public static string Command_ReportUser_ReportSent {
            get {
                return ResourceManager.GetString("Command_ReportUser_ReportSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instar Auto Member System.
        /// </summary>
        public static string Embed_AMS_Footer {
            get {
                return ResourceManager.GetString("Embed_AMS_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instar Paging System.
        /// </summary>
        public static string Embed_Page_Footer {
            get {
                return ResourceManager.GetString("Embed_Page_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instar Message Reporting System.
        /// </summary>
        public static string Embed_UserReport_Footer {
            get {
                return ResourceManager.GetString("Embed_UserReport_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://spacegirl.s3.us-east-1.amazonaws.com/instar.png.
        /// </summary>
        public static string InstarLogoUrl {
            get {
                return ResourceManager.GetString("InstarLogoUrl", resourceCulture);
            }
        }
    }
}
